services:
  postgres:
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=auctions
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postresql/data
  
  mongodb:
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=SearchDb
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpw
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/mongodb/data
  
  rabbitmq:
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  
  auctionservice:
    container_name: auctionservice
    ports:
      - 7001:80
    depends_on:
      - postgres
      - mongodb
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - 
  
volumes:
    pgdata:
    mongodata: