services:
  postgres:
    image: postgres

  mongodb:
    image: mongo
  
  rabbitmq:
    image: rabbitmq:3-management-alpine

  auctionservice:
    image: auctionservice
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
  searchservice:
    image: searchservice
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile

  identityservice:
    image: identityservice
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile

  gatewayservice:
    image: gatewayservice
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
